
#ifndef SC_PATHPLAN_SC_ALGORITHMTOOLS_SC_ALGORITHMTOOLS_H_
#define SC_PATHPLAN_SC_ALGORITHMTOOLS_SC_ALGORITHMTOOLS_H_

#include "../cg_src/r_cg_macrodriver.h"   //uint'_t

#endif /* SC_PATHPLAN_SC_ALGORITHMTOOLS_SC_ALGORITHMTOOLS_H_ */
